spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cashpilot


  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true

    
    gateway:
      routes:
        - id: envoy_proxy_route
          uri: http://localhost:10000
          predicates:
            - Path=/**


server:
  port: 9092


logging:
  level:
    ROOT: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
